# Generated by Django 6.0.3 on 2026-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
