# Generated by Django 6.0.3 on 2026-05-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'مستخدم عادي'), ('reviewer', 'مراجع أكاديمي'), ('moderator', 'مشرف محتوى'), ('admin', 'مسؤول')], default='user', max_length=20),
        ),
    ]
