# Generated by Django 6.0.3 on 2026-03-16 10:32

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='articles/pdfs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_review', 'Under Review'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('institutional', 'Institutional')], default='public', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('read_time', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('citations_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
